---
# tasks file for add-users
- name: add users
  user:
    name: "{{ item.os_user }}"
    shell: /bin/bash
    password: "{{ item.os_user_pw | password_hash('sha512') }}"
    update_password: on_create
  loop: "{{ add_user }}"
- name: add ssh keys
  authorized_key:
    user: "{{ item.os_user }}"
    state: present
    key: "{{ lookup('file', item.ssh_key_file) }}"
  loop: "{{ add_user }}"
 # loop:
 #   - "{{ add_user }}"
#- name: add to inventory
#  add_host:
#    name: "{{ item }}"
#    groups: prod
#    ansible_user: "{{ os_user }}"
#    ansible_python_interpreter: /usr/bin/python3
#  loop: 
#    - "{{ ansible_hostname }}"